-- comentarios
-- A linha abaixo cria o banco
DROP DATABASE SRAEREOS;
create database SRAEREOS;
-- escolhe o banco de dados
use SRAEREOS; 
-- dropA tabelas
DROP TABLE VOO_RESERVA CASCADE;
DROP TABLE RESERVA CASCADE;
DROP TABLE VOO CASCADE;
drop table companhia cascade;
DROP TABLE PASSAGEIRO;
DROP TABLE A_DESTINO;
DROP TABLE A_ORIGEM;
drop table aviao;


create table passageiro(
CPF INT(11) NOT NULL auto_increment,
NOME VARCHAR(50) NOT NULL,
RG INT(7) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
NACIONALIDADE VARCHAR(45) NULL,
SENHA VARCHAR(8) NOT NULL,
LOGIN VARCHAR(15) NOT NULL unique,
primary key (CPF)
)ENGINE = innodb;

SELECT * FROM PASSAGEIRO;
-- DADOS PASSAGEIROS
-- Creat
insert into passageiro(CPF,NOME,RG,EMAIL,DATANASCIMENTO,NACIONALIDADE,SENHA,LOGIN)
VALUES (78996655,'JOZIEL CARLOS',898788,'JOZIEL@GMAIL.COM','1995-05-05','BRASILEIRO','123','admin');
insert into passageiro(CPF,NOME,RG,EMAIL,DATANASCIMENTO,NACIONALIDADE,SENHA,LOGIN)
VALUES (56633222,'PEDRO CARLOS',1234565,'PEDRO@GMAIL.COM','1995-12-03','BRASILEIRO','123','admin2');
insert into passageiro(CPF,NOME,RG,EMAIL,DATANASCIMENTO,NACIONALIDADE,SENHA,LOGIN)
VALUES (65852245,'PEDRO JOSE',7456321,'PEDROJO@GMAIL.COM','2002-01-03','BRASILEIRO','123','admin3');

-- CRIA TABELA AEROPORTO DESTINO

CREATE TABLE A_DESTINO(
IDDESTINO INT PRIMARY KEY AUTO_INCREMENT,
LOCAL_DESTINO VARCHAR(50)NOT NULL
)ENGINE = innodb;

INSERT INTO A_DESTINO(LOCAL_DESTINO)
VALUES('SÃO PAULO');
INSERT INTO A_DESTINO(LOCAL_DESTINO)
VALUES('BRASÍLIA');
INSERT INTO A_DESTINO(LOCAL_DESTINO)
VALUES('RIO DE JANEIRO');


SELECT * FROM A_DESTINO;


-- CRIA TABELA AEROPORTO ORIGEM

CREATE TABLE A_ORIGEM(
IDORIGEM INT PRIMARY KEY AUTO_INCREMENT,
LOCAL_ORIGEM VARCHAR(50)NOT NULL
)ENGINE = innodb;

INSERT INTO A_ORIGEM(LOCAL_ORIGEM)
VALUES('AMAZONAS');
INSERT INTO A_ORIGEM(LOCAL_ORIGEM)
VALUES('SANTA CATARINA');
INSERT INTO A_ORIGEM(LOCAL_ORIGEM)
VALUES('CUIABA');

SELECT * FROM A_ORIGEM


-- CRIA TABELA RESERVA

 create TABLE RESERVA(
  idRESERVA INT auto_increment,
  DATARESERVA DATE NOT NULL,
  QTD_PASSAGEIRO INT(1) NOT NULL,
  VALOR FLOAT(8) NOT NULL,
  IDORIGEM int not null,
  IDDESTINO int not null,
  CPF int(11) not null,
  primary key (idRESERVA),
  foreign key (IDORIGEM) references A_ORIGEM (IDORIGEM),
  foreign key (IDDESTINO) references A_DESTINO (IDDESTINO),
  foreign key (CPF) references passageiro (CPF)
);

insert into RESERVA(DATARESERVA,QTD_PASSAGEIRO,VALOR,IDorigem,IDdestino,cpf)
VALUES ('2002-01-03',5,2500.0,2,3,78996655);

insert into RESERVA(DATARESERVA,QTD_PASSAGEIRO,VALOR,IDorigem,IDdestino,cpf)
VALUES ('2017-05-09',3,1500.0,3,2,65852245);

SELECT *FROM A_DESTINO;
SELECT*FROM A_ORIGEM;
SELECT*FROM PASSAGEIRO;
SELECT*FROM RESERVA;

CREATE TABLE AVIAO(
idAVIAO INT(6) NOT NULL,
MODELO VARCHAR(15) NOT NULL,
QTD_ASSENTOS INT(3) NOT NULL,
PRIMARY KEY (idAVIAO)
)ENGINE = InnoDB;

INSERT INTO AVIAO(idAVIAO,MODELO,QTD_ASSENTOS)
VALUES(15,'AIRBUS A380',350);
INSERT INTO AVIAO(idAVIAO,MODELO,QTD_ASSENTOS)
VALUES(25,'AIRBUS A320',200);
INSERT INTO AVIAO(idAVIAO,MODELO,QTD_ASSENTOS)
VALUES(35,'BOEING 727',230);


CREATE TABLE COMPANHIA(
idCOMPANHIA INT(4) NOT NULL AUTO_INCREMENT,
  NOME_COMP VARCHAR(45) NOT NULL,
  idAVIAO INT (6) NOT NULL,
  PRIMARY KEY (idCOMPANHIA),
  FOREIGN KEY (idAVIAO) REFERENCES AVIAO (idAVIAO)
  )ENGINE = InnoDB;
  
  SELECT*FROM COMPANHIA;
  
  INSERT INTO COMPANHIA(NOME_COMP,idAVIAO)
  VALUES ('TAM',25);
  INSERT INTO COMPANHIA(NOME_COMP,idAVIAO)
  VALUES ('GOL',25);
  INSERT INTO COMPANHIA(NOME_COMP,idAVIAO)
  VALUES ('AZUL',35);



CREATE TABLE VOO(
IDVOO INT (6) NOT NULL AUTO_INCREMENT,
IDCOMPANHIA INT (4) NOT NULL, 
PRIMARY KEY (IDVOO),
FOREIGN KEY (IDCOMPANHIA) REFERENCES COMPANHIA (idCOMPANHIA)
)ENGINE = InnoDB;

INSERT INTO VOO(IDCOMPANHIA)
VALUES (2);
INSERT INTO VOO(IDCOMPANHIA)
VALUES (3);
INSERT INTO VOO(IDCOMPANHIA)
VALUES (1);


CREATE TABLE VOO_RESERVA (
  IDVOO INT(6) NOT NULL,
  idRESERVA INT NOT NULL,
  FOREIGN KEY (IDVOO) REFERENCES VOO (IDVOO),
  FOREIGN KEY (idRESERVA) REFERENCES RESERVA (idRESERVA)
);

SELECT * FROM RESERVA INNER JOIN VOO ON (RESERVA.idRESERVA = VOO.IDVOO);

